@startuml

start

:Define task - goal, requirements and output;

:Implement task - follow guidelines and use best practices;

:Verify task - requirements, guidelines, best practices and output?;

:Review task - improvement possible?;

@enduml
